export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INPUTTEXT = 'INPUTTEXT';
export const COMMENT_CREATE = 'COMMENT_CREATE';
export const COMMENT_UPDATE = 'COMMENT_UPDATE';
